### PR TITLE
Create mining engine boilerplate

### PR DESCRIPTION
**Pull request by celinanperalta**
Resolves OAP-12

### CODE REVIEW

**Comment by eshellman** [comment]
if you think it might be easier to use a seperate repo, they're cheap. In particular, do you think the mining engine will run somewhere different from other stuff in the repo?

**Comment by celinanperalta** [comment]
The team preferred a monorepo over a multirepo for code management, but the mining engine will run separately from the web app once we get to that point.

**Comment by eshellman** [comment]
do you envision using git for deployment?

**Comment by eshellman** [comment]
or github actions for testing?

**Comment by celinanperalta** [comment]
Yes to both

**Pull request merged**
