### PR TITLE
Fix self-signed cert error

### PR DESCRIPTION
**Pull request by celinanperalta**

### CODE REVIEW

**Comment by eshellman** [comment]
why not use ~/private ? (obviously we cant have the certs in git unless you encrypt them) and it's a PITA to keep getting the deployed repo dirty

**Comment by eshellman** [comment]
also I think permissions should be 744

**Comment by eshellman** [comment]
we shouldn't need the entire certificate store in the container, as there's only one host we ever need to check a cert for.

**Comment by eshellman** [comment]
also the container probably gets a cert store via apt-get - check that you're not over-writing

**Comment by eshellman** [comment]
I think you can bind mount the ~/.ssh directory (docker run -v) too instead of copying it. (not sure that's the right tning to do though, that makes more sense for logs

**Comment by celinanperalta** [comment]
yep, currently revising to mount instead of copy.

**Comment by celinanperalta** [comment]
Also, our `.crt` does not need to be and should not be checked into git

**Comment by eshellman** [comment]
either use /private or add /certificates to gitignore

**Comment by eshellman** [comment]
Shouldn't api/certificates/dummy-cert.crt be gitignored?

**Review by eshellman — APPROVED** [review]
let's see if it works!

**Pull request merged**
